@startuml
' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

entity "business_category" as e_business_category {
  *business_category_id : number <<generated>>
  --
  *business_category_name : text
}

entity "article_category" as e_article_category {
  *article_category_id : number <<generated>>
  --
  *article_category_name : text
  *business_category_id : number <<FK>>
}

entity "article" as e_article {
  *article_id : number <<generated>>
  --
  *article_name : text
  *article_cost_unit : number
  *article_cost_dozen : number
  *article_description : text
  *article_state : text
  *article_details : text
  *business_category_id : number <<FK>>
  *article_category_id : number <<FK>>

}

entity "article_photos" as e_article_photos {
  *article_photos_id : number <<generated>>
  --
  *article_photo : text
  *article_id : number <<FK>>
}

entity "location_photo" as e_location_photo {
  *location_photo_id : number <<generated>>
  --
  *location_photo_photo : text
  *location_id:number <<FK>>
}
entity "location" as e_location {
 *location_id : number <<generated>>
  --
 *location_coordinates:text
 *location_description:text
 *location_direction:text
 *business_id:number <<FK>>
}

entity "business_association" as e_business_association {
*business_association_id:number<<generated>>
--
*business_association_name:text
*business_association_leader:text
}

entity "business" as e_business{
*business_id:number <<generated>>
--
*business_name:text
*business_description:text
*user_id:number <<FK>>
*business_category_id:number <<FK>>
*business_association_id:number <<FK>>
}

e_location_photo}|..e_location
e_location}|..||e_business
e_business}|..||e_business_association
e_business}|..||e_article
e_business_category}|..||e_business
e_business_category }|.. e_article_category
e_article_category }|.. e_article
e_article ..|| e_article_photos
@enduml